Repository accordproject/template-studio-v2, pull requests merged in 2019-11, with the labels that each got.

#151 chore(package): increment cicero-ui
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#152 fix(*): Remove clauseTemplate from clauseTemplatesState upon deletion…
  src/actions/clauseTemplatesActions.js
  src/actions/constants.js
  src/reducers/clauseTemplatesReducer.js
  src/sagas/contractSaga.js
Labels: Difficulty: Medium, Type: Bug 🐛

#157 feat(src): swap contribute banner with icon - I106
  package-lock.json
  src/containers/Header/index.js
  src/index.css
  src/index.html
Labels: Difficulty: Starter, Type: Enhancement ✨

#120 feat(*): add welcome page - I116
  assets/SearchAlternate.svg
  src/actions/appActions.js
  src/actions/constants.js
  src/containers/App/index.js
  src/containers/TemplateLibrary/index.js
  src/containers/Welcome/index.js
  src/containers/Welcome/styles.js
  src/index.css
  src/reducers/appReducer.js
  src/utilities/navigateClause.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Feature Request 🛍️
