Repository accordproject/template-studio-v2, pull requests merged in 2019-06, with the labels that each got.

#44 fix(package): fix npm vulnerabilities
  package-lock.json
  package.json
Labels: bug, good first issue

#37 feat(*): add clause to contract
  package-lock.json
  package.json
  src/actions/contractActions.js
  src/actions/templatesActions.js
  src/containers/App/index.js
  src/containers/ContractEditor/index.js
  src/containers/TemplateLibrary/index.js
  src/reducers/contractReducer.js
  src/sagas/contractSaga.js
  src/sagas/rootSaga.js
  src/sagas/templatesSaga.js
  src/selectors/contractSelectors.js
Labels: enhancement

#45 fix(build): increase max size to fix build
  package.json
Labels: bug

#47 docs(README): update netlify badge
  README.md
Labels: bug

#51 chore(ContractEditor): update to new version of editor to allow multiline clauses
  package-lock.json
  package.json
  src/sagas/templatesSaga.js
Labels: bug

#48 docs(*): update guidelines for contributions - I46
  CONTRIBUTING.md
  DEVELOPERS.md
  LICENSE
  README.md
  assets/APLogo.png
Labels: enhancement

#50 feat(ErrorModal): modal for app errors
  src/actions/appActions.js
  src/actions/contractActions.js
  src/actions/templatesActions.js
  src/containers/App/__snapshots__/index.test.js.snap
  src/containers/App/index.js
  src/containers/ErrorModal/__snapshots__/index.test.js.snap
  src/containers/ErrorModal/index.js
  src/containers/ErrorModal/index.test.js
  src/reducers/appReducer.js
  src/reducers/contractReducer.js
  src/reducers/templatesReducer.js
  src/sagas/contractSaga.js
  src/sagas/templatesSaga.js
  src/sagas/tests/templatesSaga.test.js
  src/store.js
Labels: enhancement

#53 fix(addToContract): add clause at current selected position
  src/sagas/templatesSaga.js
Labels: bug
