Repository accordproject/template-studio-v2, pull requests merged in 2019-10, with the labels that each got.

#91 docs(README): fix grammar
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#95 Update README.md for issue #94
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#97 docs(README): centered logo, adds slack badge, adds license badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#99 Docs(README): Add netlify preview badge for templatestudio V2 - 94
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#104 fix(utilities): correct offset for scroll to clause - I79
  src/utilities/navigateClause.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Bug 🐛

#117 feat(docs): add ecosystem table
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#119 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#123 fix(containers): add css related to FireFox scrollbar - I115
  src/containers/ClauseTemplate/ClauseExampleTextEditor.js
  src/containers/ClauseTemplate/ClauseGrammarEditor.js
  src/containers/ContractEditor/index.js
  src/containers/LeftNav/index.js
  src/containers/TemplateLibrary/index.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Bug 🐛

#130 Upgrade dependencies and style block quotes
  package-lock.json
  package.json
  src/index.css
Labels: Type: Enhancement ✨, Type: Feature Request 🛍️

#133 fix: color contrast a11y
  package-lock.json
  src/containers/App/themeConstants.js
Labels: A11Y 🔓, Difficulty: Starter, Hacktoberfest

#132 style(src): update code block styling
  src/index.css
Labels: Difficulty: Starter, Hacktoberfest

#143 chore(package): increment cicero-ui
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠
