Repository accordproject/template-studio-v2, pull requests merged in 2019-05, with the labels that each got.

#17 feat(src): implement logger and adjust import - I4
  package-lock.json
  package.json
  src/TemplateStudio/index.js
  src/index.js
  src/sagas/index.js
Labels: bug, enhancement

#20 fix(src): import contract editor code and modularize - I4
  package-lock.json
  package.json
  src/containers/App/__snapshots__/index.test.js.snap
  src/containers/App/index.js
  src/containers/App/index.test.js
  src/containers/ContractEditor/index.js
  src/containers/TemplateLibrary/index.js
  src/index.js
Labels: enhancement

#28 docs(*): documentation for this repository - I27
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
  markdown-license.txt
Labels: good first issue

#30 refactor(TemplateLibrary): refactor TemplateLibrary into container co…
  src/containers/App/index.js
  src/containers/TemplateLibrary/index.js
Labels: enhancement

#34 chore(linter): update clausehq/eslint-config to version with react hooks
  package-lock.json
  package.json
Labels: enhancement

#32 test(sagas): initiate testing for current sagas - I-22
  package-lock.json
  package.json
  src/containers/App/__snapshots__/index.test.js.snap
  src/sagas/logicSaga.js
  src/sagas/rootSaga.js
  src/sagas/sampleSaga.js
  src/sagas/tests/logicSaga.test.js
  src/sagas/tests/modelSaga.test.js
  src/sagas/tests/sampleSaga.test.js
  src/sagas/tests/templatesSaga.test.js
  src/utilities/test/sagaTest.js
Labels: enhancement, help wanted

#36 feat(ContractEditor): add markdown to store and render from store
  package-lock.json
  package.json
  src/actions/contractActions.js
  src/containers/App/__snapshots__/index.test.js.snap
  src/containers/ContractEditor/index.js
  src/reducers/contractReducer.js
  src/store.js
  webpack.config.js
Labels: enhancement
